# Generated by Django 4.2.7 on 2023-12-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='d_o_b',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_img',
            field=models.ImageField(default='blank_profile_picture.png', null=True, upload_to='profile_images'),
        ),
    ]
