# Generated by Django 4.2.7 on 2023-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_students_address_alter_students_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='profile_img',
            field=models.ImageField(default='blank_profile_picture.jpg', null=True, upload_to='profile_images'),
        ),
    ]
