# Generated by Django 4.2.7 on 2023-12-01 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_students_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='d_o_b',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
