# Generated by Django 4.2.7 on 2023-12-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_students_address_alter_students_d_o_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courses'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subjects'),
        ),
    ]
