# Generated by Django 4.2.7 on 2023-12-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_teachers_address_alter_teachers_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='d_o_b',
            new_name='dob',
        ),
    ]
