# Generated by Django 4.2.7 on 2023-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_d_o_b_students_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetables',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetables',
            name='type_of_class',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab')], default='Lecture', max_length=10),
        ),
    ]
