# Generated by Django 4.2.7 on 2023-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timetables_room_no_timetables_type_of_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='type_of_class',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], default='Lecture', max_length=10),
        ),
    ]
