# Generated by Django 4.2.7 on 2023-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_timetables_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
