# Generated by Django 4.2.7 on 2023-12-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendance_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='percentage',
        ),
    ]
