# Generated by Django 4.2.7 on 2023-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_attendance_class_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
