# Generated by Django 4.2.7 on 2023-12-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_attendance_class_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='percentage',
        ),
    ]
