# Generated by Django 4.2.7 on 2023-12-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_attendance_date_attendance_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='teacher_user',
            new_name='user',
        ),
    ]
