# Generated by Django 4.2.7 on 2023-12-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_course_students_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachers'),
        ),
    ]
